### PR TITLE
Use http Keep-Alive, else BigQuery queries are ~seconds slower than necessary

### PR DESCRIPTION
**Pull request by jdanbrown**
- Before (without Keep-Alive): ~3-7s for BigQuery `select 3` with an already cached result
- After (with Keep-Alive): ~1.5-3s
- Query sends these 6 http requests and runtime appears to be dominated by network RTT:
```
http: method[POST], url[https://www.googleapis.com/bigquery/v2/projects/foo-bar/jobs/], body[{"kind": "bigquery#job", "configuration": {"priority": "INTERACTIVE", "query": {"allowLargeResults": false, "useLegacySql": false, "useQueryCache": true, "query": "select 3", "userDefinedFunctionResources": []}, "dryRun": false}}]
http: method[GET], url[https://www.googleapis.com/bigquery/v2/projects/foo-bar/queries/job_sIi1HRqfyHkRB5_MkfWFjtZ60XM?startIndex=0&timeoutMs=30000&maxResults=0], body[None]
http: method[GET], url[https://www.googleapis.com/bigquery/v2/projects/foo-bar/jobs/job_sIi1HRqfyHkRB5_MkfWFjtZ60XM], body[None]
http: method[GET], url[https://www.googleapis.com/bigquery/v2/projects/foo-bar/datasets/_2f96775300d8858559d2bd23c05bad0392345e30/tables/anon921947a4e6645dc2b34411c365f9a45e0895d5a4], body[None]
http: method[GET], url[https://www.googleapis.com/bigquery/v2/projects/foo-bar/datasets/_2f96775300d8858559d2bd23c05bad0392345e30/tables/anon921947a4e6645dc2b34411c365f9a45e0895d5a4], body[None]
http: method[GET], url[https://www.googleapis.com/bigquery/v2/projects/foo-bar/datasets/_2f96775300d8858559d2bd23c05bad0392345e30/tables/anon921947a4e6645dc2b34411c365f9a45e0895d5a4/data?maxResults=25], body[None]
```

### CODE REVIEW

**Comment by jdanbrown** [comment]
Oops, broken tests—I think I broke the `httplib2` mocking in tests/_util/http_tests.py:
```
======================================================================
ERROR: test_get_request_is_invoked (_util.http_tests.TestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/danb/src/pydatalab/datalab/utils/_http.py", line 139, in request
    return json.loads(str(content, encoding='UTF-8'))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/danb/miniconda3/lib/python3.6/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/Users/danb/src/pydatalab/tests/_util/http_tests.py", line 30, in test_get_request_is_invoked
    Http.request('http://www.example.org')
  File "/Users/danb/src/pydatalab/datalab/utils/_http.py", line 143, in request
    raise Exception('Failed to process HTTP response.')
Exception: Failed to process HTTP response.
```

Can you help me understand what's going wrong? I manually tested my change on a few real queries and it appears to work.

**Comment by yebrahim** [comment]
The problem is what's being mocked is the call to `httplib2.Http.request`, which is a call to a new instance (since `.request` is a regular method not a static one), but what your changes are using is a call to a static property `google.datalab.utils._http.Http.http.request`. So what you want to mock instead is just that.

Try changing the mock statements to the following:
`@mock.patch('google.datalab.utils._http.Http.http.request')`

**Comment by jdanbrown** [comment]
@yebrahim Thanks! Tests pass now.

**Comment by yebrahim** [comment]
Awesome! Thanks for fixing this. :)

**Pull request merged**
