### PR TITLE
Resolve issue where the legacy bq.Query command would raise TypeError

### PR DESCRIPTION
**Pull request by parthea**
Steps to reproduce
```
df = bq.Query("SELECT * FROM ")

----> 1 df = bq.Query("SELECT * FROM ")

/usr/local/lib/python2.7/dist-packages/datalab/bigquery/_query.pyc in __init__(self, sql, context, values, udfs, data_sources, **kwargs)
    104     included_udfs = set([])
    105 
--> 106     tokens = datalab.data.tokenize(self._sql)
    107     udf_dict = {udf.name: udf for udf in udfs}
    108 

/usr/local/lib/python2.7/dist-packages/datalab/data/_utils.pyc in tokenize(sql)
    155     A list of strings corresponding to the groups above.
    156   """
--> 157   return list(_next_token(sql))

/usr/local/lib/python2.7/dist-packages/datalab/data/_utils.pyc in _next_token(sql)
    129 
    130     i += 1
--> 131     while i < len(sql) and not end_checker(sql, i):
    132       i += 1
    133 

TypeError: 'bool' object is not callable
```

This issue was a regression introduced in #315 during refactoring.

### CODE REVIEW

**Comment by parthea** [comment]
I'll comment when this is ready for review. I accidentally missed running the legacy tests in my local testing of #315.  In addition, the legacy tests were not enabled on Travis. I'm going to tackle the broken legacy tests this weekend so we can re-enable them on Travis.

**Comment by yebrahim** [comment]
Thanks for catching that. I think we should check in the fix on its own for now, then fix tests, because the legacy `datalab` package is broken.

**Comment by parthea** [comment]
Done. Travis is green.  I'm going to submit a separate PR to fix/enable unit tests for the legacy `datalab` package (issue #322).

**Comment by yebrahim** [comment]
Great. Thanks.

**Pull request merged**
