### PR TITLE
Resolve issue where exception occurs when running bigquery.execute with empty query result.

### PR DESCRIPTION
**Pull request by HaipengSu**
Resolve issue googledatalab/datalab#1332

### CODE REVIEW

**Comment by HaipengSu** [comment]
I have signed the CLA. thx

**Comment by yebrahim** [comment]
Thanks for the fix @HaipengSu. Please just comment with the string "I signed it!" since this is an automated approval. :)

Otherwise, looks good. I'll merge once it passes the bot.

**Comment by HaipengSu** [comment]
I signed it!

**Comment by yebrahim** [comment]
I think it needs a new comment. :)

**Comment by HaipengSu** [comment]
I signed it!

**Comment by HaipengSu** [comment]
@yebrahim Thank you so much~~~~ :)  and glad I can help too.

**Pull request merged**
