### PR TITLE
Resolve issue where datalab build fails when installing pyDatalab

### PR DESCRIPTION
**Pull request by parthea**
This PR fixes issue googledatalab/datalab#1160 in my local setup with the following changes:

- In setup.py, extend setuputils install to include additional pip installations for tensorflow and cloud ml similar to https://docs.python.org/2/distutils/extending.html.
- In setup.py, `platform.linux_distribution()[0]` was returning `'debian'` on Ubuntu. On my machine, `pip._vendor.distro.linux_distribution()[0]` provides the correct distribution `'Ubuntu'`.

```
>>> import platform
>>> platform.linux_distribution()[0]
'debian'
```

```
>>> from pip._vendor import distro
>>> distro.linux_distribution()[0]
u'Ubuntu'
```

### CODE REVIEW

**Comment by yebrahim** [comment]
Interesting. Why does this fix it though? I don't see any differences between this and installing TF and CloudML separately in the setup script.

**Comment by parthea** [comment]
> Why does this fix it though? I don't see any differences between this and installing TF and CloudML separately in the setup script.

Although the build failure doesn't appear when I apply the changes in this PR, I wasn't able to find/explain the root cause. I'm going to close this PR so we can dig into this a bit more.

I prefer `pip._vendor.distro.linux_distribution()[0]` over `platform.linux_distribution()[0]` based on the output of these 2 commands on my Ubuntu laptop. The build failure exists regardless of whether the Linux distribution is detected correctly.

**Comment by parthea** [comment]
I noticed that the build failure doesn't appear when I comment out the following line in setup.py. Hopefully, this is a clue to help find the root cause.

```
  pip.main(['install', 'https://storage.googleapis.com/cloud-ml/sdk/cloudml.latest.tar.gz'])
```

https://github.com/googledatalab/pydatalab/blob/master/setup.py#L132

**Comment by yebrahim** [comment]
Honestly I'm not sure if it's worth spending more time investigating this, I think we need a workaround. 

I also noticed the error goes away if we use an older version of pip (<9), and I've seen some other threads about this being a bug in pip 9+, but I still can't put my hands on the exact root cause. Either fix is fine to me. I'll reopen your PR so we keep our options open.

**Comment by yebrahim** [comment]
Can't reopen, you deleted your branch. :)

**Comment by parthea** [comment]
Done.

It would be interesting to see if the issue re-appears with this workaround. I would be happy to dig into this issue further if we are interested to find the root cause. I am really curious about the root cause as well.

**Comment by yebrahim** [comment]
Ok so CloudML SDK released a new version on Friday, and this is what's causing the break. I'm checking to see what our options are, but for the time being, I don't think further digging will get us anywhere. :)

**Comment by yebrahim** [comment]
I just sent a workaround to downgrade pip: https://github.com/googledatalab/datalab/pull/1162, since this one is breaking tests for some reason. I suspect the reason is CloudML isn't installing properly, as I couldn't get it to install inside the Datalab container. I'll close this PR. Thanks for digging into this @parthea.

**Pull request closed without merging**
