### PR TITLE
Bumping google.cloud from 0.19 to 0.27

### PR DESCRIPTION
**Pull request by jpvelez**
Hi there,

Having similar version collision problems as in the previous PR. Was hoping we could bump `google.cloud` dependency from 0.19 to 0.27

### CODE REVIEW

**Comment by yebrahim** [comment]
Looks like this is causing some auth issues. @jpvelez is this working for you locally?

**Comment by jpvelez** [comment]
Yep! I installed this patched version from my Github account and `%bq` magic works fine.

**Comment by jpvelez** [comment]
I'm sure this is pretty low-priority for you, but I was just wondering how involved it would be to fix the auth issues and do a release that bumps the version? Running our notebooks at Spotify off of a patched internal fork at the moment. Thank you!

**Comment by chmeyers** [comment]
I'll get someone to look at it.

**Comment by yebrahim** [comment]
The auth issues are because `google-cloud` [moved away](https://github.com/GoogleCloudPlatform/google-cloud-python/pull/2726/) from using `oauth2client` in favor of `google.auth`, so the credentials object created by our `get_credentials` function is no longer supported.
We need to switch to `google.auth` anyway since `oauth2client` is getting deprecated, I'll see if it's straightforward to do that.

**Comment by yebrahim** [comment]
Closing this in favor of https://github.com/googledatalab/pydatalab/pull/516, which also bumps up google.cloud.

**Pull request closed without merging**
